[package]
name = "tethys"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11.3"
log = "0.4"
wgpu = "0.20.1"
bytemuck = { version = "1.12", features = [ "derive" ] }
